const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST"

const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"

const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR"

const GET_PROJECT_BY_SLUG_REQUEST = "GET_PROJECT_BY_SLUG_REQUEST"

const GET_PROJECT_BY_SLUG_SUCCESS = "GET_PROJECT_BY_SLUG_SUCCESS"

const GET_PROJECT_BY_SLUG_ERROR = "GET_PROJECT_BY_SLUG_ERROR"


export {
    GET_PROJECTS_ERROR,
    GET_PROJECTS_REQUEST,
    GET_PROJECTS_SUCCESS,
    GET_PROJECT_BY_SLUG_ERROR,
    GET_PROJECT_BY_SLUG_REQUEST,
    GET_PROJECT_BY_SLUG_SUCCESS
}